#: kivy 2.0.0

<AnswerButton>
    is_correct: False
    halign: "center"
    font_size: "18sp"
    size_hint_x: 1
    # md_bg_color: app.theme_cls.primary_color
    # text_color: 1, 1, 1, 1

<QuizBox>
    orientation: "vertical"

    # Label hiển thị câu hỏi
    question_label: question_label
    answer_btn1: answer_btn1
    answer_btn2: answer_btn2
    answer_btn3: answer_btn3
    answer_btn4: answer_btn4


    MDLabel:
        id: question_label
        text: "Câu hỏi sẽ hiển thị ở đây"
        font_name: "res/fonts/Roboto.ttf"
        halign: "center"
        size_hint_y: None
        height: 50

    MDBoxLayout:
        spacing: 20
        padding: 20
        orientation: "vertical"

        MDBoxLayout:
            spacing: 20
            orientation: "horizontal"

            AnswerButton:
                id: answer_btn1
                text: "Đáp án 1"
                halign: "center"
                text_size: self.width, None
                size_hint: (1, 1)

            # Đáp án 2
            AnswerButton:
                id: answer_btn2
                text: "Đáp án 2"
                halign: "center"
                text_size: self.width, None
                size_hint: (1, 1)

        MDBoxLayout:
            spacing: 20
            orientation: "horizontal"

            AnswerButton:
                id: answer_btn3
                text: "Đáp án 3"
                halign: "center"
                text_size: self.width, None
                size_hint: (1, 1)

            # Đáp án 4
            AnswerButton:
                id: answer_btn4
                text: "Đáp án 4"
                halign: "center"
                text_size: self.width, None
                size_hint: (1, 1)

<QuizScreen>:
    quizbox: quizbox
    QuizBox:
        id: quizbox