#: kivy 2.0.0

<AnswerButton>
    is_correct: False
    halign: "center"
    font_size: "18sp"
    size_hint_x: 1
    # md_bg_color: app.theme_cls.primary_color
    # text_color: 1, 1, 1, 1

<QuizBox>
    orientation: "vertical"

    # Label hiển thị câu hỏi
    question_label: question_label
    answer_btn1: answer_btn1
    answer_btn2: answer_btn2
    answer_btn3: answer_btn3
    answer_btn4: answer_btn4


    MDLabel:
        id: question_label
        text: "Câu hỏi sẽ hiển thị ở đây"
        font_name: "res/fonts/Roboto.ttf"
        halign: "center"
        size_hint_y: None
        height: 50

    MDBoxLayout:
        spacing: 20
        padding: 20
        orientation: "vertical"

        MDBoxLayout:
            spacing: 20
            orientation: "horizontal"

            AnswerButton:
                id: answer_btn1
                text: "Đáp án 1"
                halign: "center"
                text_size: self.width, None
                size_hint: (1, 1)

            # Đáp án 2
            AnswerButton:
                id: answer_btn2
                text: "Đáp án 2"
                halign: "center"
                text_size: self.width, None
                size_hint: (1, 1)

        MDBoxLayout:
            spacing: 20
            orientation: "horizontal"

            AnswerButton:
                id: answer_btn3
                text: "Đáp án 3"
                halign: "center"
                text_size: self.width, None
                size_hint: (1, 1)

            # Đáp án 4
            AnswerButton:
                id: answer_btn4
                text: "Đáp án 4"
                halign: "center"
                text_size: self.width, None
                size_hint: (1, 1)

<QuizScreen>:
    quizbox: quizbox
    QuizBox:
        id: quizbox

<AddQuizScreen>:
    name: "add_quiz_screen"
    question_text: question_text
    answer_text: answer_text
    option1_text: option1_text
    option2_text: option2_text
    option3_text: option3_text

        # size_hint_y: None
        # height: self.texture_size[1]
        # padding_y: dp(20)

    MDBoxLayout:
        orientation: "vertical"
        padding: dp(16)
        spacing: dp(12)

        MDLabel:
            text: "Thêm câu hỏi mới"
            halign: "center"
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            font_style: "H4"

        MDTextField:
            id: question_text
            hint_text: "Câu hỏi"
            mode: "rectangle"
            height: dp(100)
            multiline: True

        MDTextField:
            id: answer_text
            hint_text: "Đáp án"
            mode: "rectangle"
            height: dp(56)

        MDTextField:
            id: option1_text
            hint_text: "Lựa chọn 1"
            mode: "rectangle"
            height: dp(56)

        MDTextField:
            id: option2_text
            hint_text: "Lựa chọn 2"
            mode: "rectangle"
            height: dp(56)

        MDTextField:
            id: option3_text
            hint_text: "Lựa chọn 3"
            mode: "rectangle"
            height: dp(56)

        MDRectangleFlatButton:
            text: "Thêm câu hỏi"
            pos_hint: {"center_x": 0.5}
            md_bg_color: app.theme_cls.primary_color
            text_color: 1, 1, 1, 1
            size_hint: None, None
            size: dp(160), dp(44)
            on_release:
                self.parent.parent.add_quiz()
