#: kivy 2.0.0

#: include app/views/quizscreen/quizscreen.kv
#: include app/views/addquizscreen/addquizscreen.kv
#: include app/views/settingscreen/settingscreen.kv
#: include app/views/homescreen/homescreen.kv
#: include app/views/pdfscreen/pdfscreen.kv
#: include app/views/videoscreen/videoscreen.kv
#: include app/views/registerscreen/registerscreen.kv
#: include app/views/resultscreen/resultscreen.kv

MDBoxLayout:
    orientation: "vertical"

    MDTopAppBar:
        id: top_bar
        title: "Quiz App"
        left_action_items: [["arrow-left", lambda x: app.go_back()]]
        md_bg_color: app.theme_cls.primary_color

    MDScreenManager:
        id: screen_manager

        HomeScreen:
            id: home_screen
            name: "home_screen"

        VideoScreen:
            id: video_screen
            name: "video_screen"

        SettingScreen:
            id: setting_screen
            name: "setting_screen"

        PdfScreen:
            id: pdf_screen
            name: "pdf_screen"

        RegisterScreen:
            id: quiz_register_screen
            name: "quiz_register_screen"

        QuizScreen:
            id: quiz_screen
            name: "quiz_screen"

        AddQuizScreen:
            id: add_quiz_screen
            name: "add_quiz_screen"

        ResultScreen:
            id: result_screen
            name: "result_screen"