#: kivy 2.0.0

#: include app/components/widgets.kv
#: include app/views/quizscreen/quizscreen.kv
#: include app/views/settingscreen/settingscreen.kv
#: include app/views/homescreen/homescreen.kv
#: include app/views/pdfscreen/pdfscreen.kv
#: include app/views/videoscreen/videoscreen.kv
#: include app/views/registerscreen/registerscreen.kv
#: include app/views/resultscreen/resultscreen.kv

MDScreen:
    orientation: 'vertical'

    MDBottomNavigation:

        MDBottomNavigationItem:
            name: "home_tab"
            text: "Home"
            icon: "home"

            HomeScreen:
                id: home_screen

        MDBottomNavigationItem:
            name: "video_tab"
            text: "Videos"
            icon: "video"

            VideoScreen:
                id: video_screen

        MDBottomNavigationItem:
            name: "setting_tab"
            text: "Settings"
            icon: "cog"

            SettingScreen:
                id: setting_screen