#: kivy 2.0.0

#: include app/components/widgets.kv
#: include app/views/quizscreen/quizscreen.kv
#: include app/views/settingscreen/settingscreen.kv
#: include app/views/homescreen/homescreen.kv
#: include app/views/pdfscreen/pdfscreen.kv
#: include app/views/videoscreen/videoscreen.kv
#: include app/views/registerscreen/registerscreen.kv
#: include app/views/resultscreen/resultscreen.kv

MDScreen:
    orientation: 'vertical'

    MDScreenManager:
        id: screen_manager

        HomeScreen:
            id: home_screen
            name: "home_screen"

        VideoScreen:
            id: video_screen
            name: "video_screen"

        SettingScreen:
            id: setting_screen
            name: "setting_screen"