<ResultScreen>:
    name: "result_screen"
    name_label: name_label
    unit_label: unit_label
    score_label: score_label

    MDBoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 20

        MDLabel:
            text: "Bạn đã hoàn thành phần thi!"
            font_size: '24sp'
            size_hint_y: None

        MDLabel:
            id: name_label
            text: ""
            font_size: '24sp'
            size_hint_y: None

        MDLabel:
            id: unit_label
            text: ""
            font_size: '24sp'
            size_hint_y: None

        MDLabel:
            id: score_label
            text: ""
            font_size: '24sp'
            size_hint_y: None


        MDRectangleFlatIconButton:
            text: "Quay về trang chủ"
            icon: "home"
            pos_hint: {"center_x": 0.5}
            height: dp(48)
            on_release:
                app.root.ids.screen_manager.current = 'home_screen'
