<ResultScreen>:
    name: "result_screen"
    score_label: score_label


    MDBoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 20

        Image:
            # TODO: Manual scale img
            source: "res/img/trophy.png"

        MDLabel:
            text: "Bạn đã hoàn thành phần thi!"
            halign: 'center'
            font_size: '24sp'
            font_name: "res/fonts/Bangers.ttf"
            size_hint_y: None

        MDLabel:
            id: score_label
            text: "Điểm của bạn: "
            halign: 'center'
            font_size: '24sp'
            font_name: "res/fonts/Roboto.ttf"
            size_hint_y: None


        MDRectangleFlatIconButton:
            text: "Quay về trang chủ"
            icon: "home"
            pos_hint: {"center_x": 0.5}
            height: dp(48)
            font_name: "res/fonts/Roboto.ttf"
            on_release:
                app.root.ids.screen_manager.current = 'home_screen'
