<ResultScreen>:
    name: "result_screen"
    name_label: name_label
    unit_label: unit_label
    score_label: score_label

    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 20

        Label:
            text: "Bạn đã hoàn thành phần thi!"
            font_size: '24sp'
            size_hint_y: None

        Label:
            id: name_label
            text: ""
            font_size: '24sp'
            size_hint_y: None

        Label:
            id: unit_label
            text: ""
            font_size: '24sp'
            size_hint_y: None

        Label:
            id: score_label
            text: ""
            font_size: '24sp'
            size_hint_y: None

        Button:
            text: "Return to Home"
            size_hint_y: None
            height: '48dp'
            on_release:
                app.root.current = 'home_screen'
                app.root.transition.direction = 'right'