<PdfScreen>:

    BoxLayout:
        orientation: 'vertical'

        MDRaisedButton:
            text: "Chọn file"
            size_hint_y: None
            height: '40dp'
            pos_hint: {"center_x": 0.5}
            on_release: root.pick_file()

        MDScrollView:
            MDGridLayout:
                id: files_box
                cols: 2
                adaptive_height: True
                size_hint_y: None
                height: self.minimum_height
                spacing: dp(10)
                padding: dp(10)