<SettingScreen>:
    MDBoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 20

        MDTextField:
            id: max_question
            hint_text: "Maximum Questions per Quiz"
            text: str(root.max_question_text)
            font_size: '18sp'
            multiline: False
            input_filter: 'int'
            on_text_validate:
                root.max_question_text = int(self.text) if self.text.isdigit() else 10
                root.save()

        MDSlider:
            id: volume
            hint: True
            size_hint_y: None
            height: dp(10)
            value: int(root.volume * 100)
            on_value:
                root.volume = self.value / 100.0
                root.save()
                # root.value = float(self.text) if self.text.replace('.','',1).isdigit() else 1.0
                # root.save()