#: kivy 2.0.0

<RegisterScreen>:
    name_text: name_text
    unit_text: unit_text

    MDBoxLayout:
        orientation: "vertical"

        MDTextField:
            id: name_text
            hint_text: "Họ và tên"
            font_size: 32
            mode: "fill"

        MDTextField:
            id: unit_text
            hint_text: "Đơn vị"
            font_size: 32
            mode: "fill"


        MDRectangleFlatIconButton:
            text: "xác nhận"
            icon: "check"
            pos_hint: {"center_x": 0.5}
            height: dp(48)
            on_release: root.register_user()
